export {default as Basket} from "./basket/Basket"
export {default as Home} from "./home/Home"
export {default as My} from "./my/MyLayout"
export {default as MyMain} from "./my/MyMain"
export {default as AuthPage} from "./auth/AuthPage"
export {default as OrderlistLayout} from "./orderlist/OrderlistLayout"
export {default as OrderlistActive} from "./orderlist/OrderlistActive"
export {default as OrderlistArchive} from "./orderlist/OrderlistArchive"
export {default as Admin} from "./admin/Admin"
export {default as AdminOrderlistShopActive} from './admin/orderlistShop/AdminOrderlistShopActive'
export {default as AdminOrderlistShopArchive} from './admin/orderlistShop/AdminOrderlistShopArchive'
export {default as AdminOrderlistShopLayout} from './admin/orderlistShop/AdminOrderlistShopLayout'
export {default as AdminOrderlistUserActive} from './admin/orderlistUser/AdminOrderlistUserActive'
export {default as AdminOrderlistUserArchive} from './admin/orderlistUser/AdminOrderlistUserArchive'
export {default as AdminOrderlistUserLayout} from './admin/orderlistUser/AdminOrderlistUserLayout'
export {default as AdminCreate} from './admin/create/AdminCreate'
export {default as AdminDelete} from './admin/delete/AdminDelete'
export {default as AdminUpdate} from './admin/update/AdminUpdate'
export {default as AdminOther} from './admin/other/Other'
export {default as Catalog} from './catalog/Catalog'
export {default as About} from './about/About'
export {default as Category} from './category/category/Category'
export {default as CategoryLayout} from './category/layout/CategoryLayout'
export {default as Product} from './product/Product'
export {default as Shops} from './shops/Shops'
export {default as Shop} from './shop/Shop'
export {default as Purchase} from './purchase/layout/PurchaseLayout'
export {default as PurchaseStep1} from './purchase/step1/PurchaseStep1'
export {default as PurchaseStep2} from './purchase/step2/PurchaseStep2'
export {default as DeliveryAndPayment} from './deliveryAndPayment/DeliveryAndPayment'
export {default as Order} from './order/Order'
export {default as NotFound} from './notFound/NotFound'
export {default as Favourites} from './favourites/ui/Favourites'
